"""add last_humanized_at to social_accounts

Revision ID: 1a8e8a64ddda
Revises: 8e99bd4e80c1
Create Date: 2026-07-15 11:50:36.032965
"""
from alembic import op
import sqlalchemy as sa


revision = '1a8e8a64ddda'
down_revision = '8e99bd4e80c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('last_humanized_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'last_humanized_at')
    # ### end Alembic commands ###
