"""add boxphone to devices

Revision ID: 7cd3375a711f
Revises: 1a8e8a64ddda
Create Date: 2026-07-15 13:04:24.830721
"""
from alembic import op
import sqlalchemy as sa


revision = '7cd3375a711f'
down_revision = '1a8e8a64ddda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('boxphone', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'boxphone')
    # ### end Alembic commands ###
