"""add traits to accounts

Revision ID: 8e99bd4e80c1
Revises: bad8629c8f69
Create Date: 2026-07-15 11:35:12.307347
"""
from alembic import op
import sqlalchemy as sa


revision = '8e99bd4e80c1'
down_revision = 'bad8629c8f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('traits', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'traits')
    # ### end Alembic commands ###
