"""initial schema

Revision ID: bad8629c8f69
Revises: 
Create Date: 2026-07-07 21:45:47.870609
"""
from alembic import op
import sqlalchemy as sa


revision = 'bad8629c8f69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('operativo', 'inoperativo', name='proxy_status'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxies_id'), 'proxies', ['id'], unique=False)
    op.create_index(op.f('ix_proxies_status'), 'proxies', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'operador', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('proxy_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('activo', 'inactivo', 'suspendido', 'en_revision', name='device_status'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('proxy_id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporate_email', sa.String(length=150), nullable=False),
    sa.Column('corp_password_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('activo', 'inactivo', 'suspendido', 'en_revision', name='account_status'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('profile_name', sa.String(length=150), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_corporate_email'), 'accounts', ['corporate_email'], unique=True)
    op.create_index(op.f('ix_accounts_device_id'), 'accounts', ['device_id'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'tiktok', name='platform'), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('slot_number', sa.Integer(), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('activo', 'inactivo', 'suspendido', 'en_revision', name='social_status'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('humanization_status', sa.Enum('pendiente', 'en_proceso', 'hecho', name='social_humanization_status'), nullable=True),
    sa.Column('humanization_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('humanization_done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'platform', name='uq_account_platform')
    )
    op.create_index(op.f('ix_social_accounts_humanization_status'), 'social_accounts', ['humanization_status'], unique=False)
    op.create_index(op.f('ix_social_accounts_id'), 'social_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_social_accounts_platform'), 'social_accounts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_accounts_status'), 'social_accounts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_accounts_status'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_platform'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_humanization_status'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_device_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_corporate_email'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_proxies_status'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_id'), table_name='proxies')
    op.drop_table('proxies')
    # ### end Alembic commands ###
